### ISSUE TITLE
图片失真了，再哪里设置大小？

### ISSUE THREAD

**Issue by gqdy365** [MiracleXYZ/turtle_recorder#1]
图片失真了，再哪里设置大小？

**Comment by Karrrrrrrr** [comment]
Traceback (most recent call last):
  File "D:/PycharmProject1/turtle_recorder-master/example.py", line 4, in <module>
    with Recorder(main, fps=30) as peg:
  File "D:\PycharmProject1\turtle_recorder-master\turtle_recorder\turtle_recorder.py", line 14, in __enter__
    self.record()
  File "D:\PycharmProject1\turtle_recorder-master\turtle_recorder\turtle_recorder.py", line 69, in record
    self.load_animation()
  File "D:\PycharmProject1\turtle_recorder-master\turtle_recorder\turtle_recorder.py", line 46, in load_animation
    plt.imshow(img)
  File "D:\Python3.8\lib\site-packages\matplotlib\pyplot.py", line 2645, in imshow
    __ret = gca().imshow(
  File "D:\Python3.8\lib\site-packages\matplotlib\__init__.py", line 1543, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "D:\Python3.8\lib\site-packages\matplotlib\cbook\deprecation.py", line 358, in wrapper
    return func(*args, **kwargs)
  File "D:\Python3.8\lib\site-packages\matplotlib\cbook\deprecation.py", line 358, in wrapper
    return func(*args, **kwargs)
  File "D:\Python3.8\lib\site-packages\matplotlib\axes\_axes.py", line 5615, in imshow
    im.set_data(X)
  File "D:\Python3.8\lib\site-packages\matplotlib\image.py", line 693, in set_data
    raise TypeError("Image data of dtype {} cannot be converted to "
TypeError: Image data of dtype object cannot be converted to float

这是我运行example.py的时候报的错 这是什么原因
